name: Deploy quasi-web-server to MicroK8s

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: self-hosted #ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
      with:
        platforms: linux/amd64,linux/arm64

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    # - name: Install miredo
    #   run: |
    #     sudo apt install -y miredo
    #     sudo sed -i 's/ServerAddress	teredo-debian.remlab.net/ServerAddress teredo.iks-jena.de/g' /etc/miredo.conf
    #     sudo miredo
    #     cat /etc/miredo.conf
    #     sleep 1
    #     ip addr
    #     sleep 1
    #     ip addr
    #     sleep 1
    #     ip addr

    # - name: Test IPv6 connectivity
    #   run: |
    #     ping6 -c 4 ${{ secrets.SSH_HOST }} || exit "Ping is failed"

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/amd64,linux/arm64
        push: true
        tags: pavalshlyk/quasi-web-server:latest

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Deploy to MicroK8s
      env:
        KUBECONFIG: ${{ secrets.KUBECONFIG }}
      run: |
        echo "$KUBECONFIG" > kubeconfig.yaml
        export KUBECONFIG=kubeconfig.yaml
        kubectl apply -f k8s/quasi-web-server.yaml --validate=false --insecure-skip-tls-verify=true
        # kubectl apply -f k8s/nginx.yaml --validate=false
        kubectl rollout restart deployment/quasi-web-server --insecure-skip-tls-verify=true
        # kubectl rollout restart deployment/nginx
        kubectl rollout status deployment/quasi-web-server --insecure-skip-tls-verify=true
        # kubectl rollout status deployment/nginx
