name: Deploy quasi-web-server to MicroK8s

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Test IPv6 connectivity
      run: |
        curl -6 -k https://quasi.su:16443 || echo "Curl failed"
        ping6 -c 4 ${{ secrets.SSH_HOST }} || echo "Ping failed"

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: pavalshlyk/quasi-web-server:latest

    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Set up SSH tunnel
      run: |
        sudo apt-get update && sudo apt-get install -y openssh-client
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ssh_key
        chmod 600 ssh_key
        ssh -6 -i ssh_key -f -N -L 16443:localhost:16443 ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} -p ${{ secrets.SSH_PORT }}

    - name: Deploy to MicroK8s
      env:
        KUBECONFIG: ${{ secrets.KUBECONFIG }}
      run: |
        echo "$KUBECONFIG" > kubeconfig.yaml
        export KUBECONFIG=kubeconfig.yaml
        kubectl apply -f k8s/quasi-web-server.yaml --validate=false
        # kubectl apply -f k8s/nginx.yaml --validate=false
        kubectl rollout restart deployment/quasi-web-server
        # kubectl rollout restart deployment/nginx
        kubectl rollout status deployment/quasi-web-server
        # kubectl rollout status deployment/nginx
